- hosts: wobpc
  become: false
  connection: local
  vars:
    git_project_dir: /home/wob/Projects
    git_project_list:
      - url: git@github.com:swobspace/adwhois.git
      - url: git@github.com:swobspace/rails-playground.git
      - url: git@github.com:swobspace/mirco.git
      - url: git@github.com:swobspace/wobmire.git
      - url: git@github.com:swobspace/titracka.git
      - url: git@github.com:swobspace/boskop.git
      - url: git@github.com:swobspace/wobauth.git
      - url: git@github.com:swobspace/wobaduser.git
      - url: git@github.com:swobspace/wobapphelpers.git
      # - url: git@github.com:swobspace/cups-pdf-container.git

      - url: git@mintra3.marienhaus.de:mit/medv.git
        dir: mit/medv
      - url: git@mintra3.marienhaus.de:mit/common.git
        dir: mit/common
      - url: git@mintra3.marienhaus.de:mit/users.git
        dir: mit/users
      - url: git@mintra3.marienhaus.de:mit/tutorials.git
        dir: mit/tutorials
      - url: git@mintra3.marienhaus.de:mit/dbadmin.git
        dir: mit/dbadmin

      - url: git@github.com:swobspace/cocard.git
        dir: gematik/cocard
      - url: git@mintra3.marienhaus.de:projects/soapconnect.git
        dir: gematik/soapconnect
      - url: git@github.com:swobspace/kocoboot.git
        dir: gematik/kocoboot

      - url: git@mintra3.marienhaus.de:websites/mintra2
      - url: git@mintra3.marienhaus.de:websites/mintra3
      - url: git@mintra3.marienhaus.de:webapps/beschlussdb
      - url: git@mintra3.marienhaus.de:webapps/ivmessy
      - url: git@mintra3.marienhaus.de:webapps/daisy

  roles:
    - git

- hosts: wobpc
  become: false
  connection: local
  tags:
    - ansible

  vars:
    git_project_dir: /home/wob/ansible
    git_project_list:
      - url: git@mintra3.marienhaus.de:ansible/systems/medv.git
        dir: systems/medv
      - url: git@mintra3.marienhaus.de:ansible/systems/offline.git
        dir: systems/offline
      - url: git@mintra3.marienhaus.de:ansible/systems/intranet.git
        dir: systems/intranet
      - url: git@mintra3.marienhaus.de:ansible/systems/keycloak.git
        dir: systems/keycloak
      - url: git@mintra3.marienhaus.de:ansible/systems/chemocompile.git
        dir: systems/chemocompile

      - url: git@github.com:swobspace/ansible-role-system
        dir: roles/system
      - url: git@github.com:swobspace/ansible-role-podman
        dir: roles/podman
      - url: git@github.com:swobspace/ansible-role-git
        dir: roles/git

      - url: git@mintra3.marienhaus.de:ansible/roles/railsapp
        dir: roles/railsapp
      - url: git@mintra3.marienhaus.de:ansible/roles/ruby
        dir: roles/ruby
      - url: git@mintra3.marienhaus.de:ansible/roles/checkmk-agent
        dir: roles/checkmk-agent
      - url: git@mintra3.marienhaus.de:ansible/roles/apache
        dir: roles/apache
      - url: git@mintra3.marienhaus.de:ansible/roles/mh-ca-certs
        dir: roles/mh-ca-certs


  roles:
    - git

- hosts: wobpc
  become: false
  connection: local
  tags:
    - eli

  vars:
    git_project_dir: /home/wob
    git_project_list:
      - url: elix01:/data/git/home/wob/doc.git
        dir: doc

  roles:
    - git
