- hosts: wobpc
  become: false
  connection: local
  vars:
    git_project_dir: /home/wob/Projects
    git_project_list:
      - url: git@github.com:swobspace/adwhois.git
      - url: git@github.com:swobspace/rails-playground.git
      - url: git@github.com:swobspace/mirco.git
      - url: git@github.com:swobspace/titracka.git
      - url: git@github.com:swobspace/boskop.git
      - url: git@github.com:swobspace/wobauth.git
      - url: git@github.com:swobspace/wobaduser.git
      - url: git@github.com:swobspace/wobapphelpers.git
      - url: git@github.com:swobspace/cups-pdf-container.git
      - url: git@mintra3.marienhaus.de:mit/medv.git
        dir: mit/medv
      - url: git@mintra3.marienhaus.de:mit/common.git
        dir: mit/common
      - url: git@mintra3.marienhaus.de:mit/users.git
        dir: mit/users
      - url: git@mintra3.marienhaus.de:mit/tutorials.git
        dir: mit/tutorials
      - url: git@mintra3.marienhaus.de:mit/dbadmin.git
        dir: mit/dbadmin
      - url: git@github.com:swobspace/cocard.git
        dir: gematik/cocard
      - url: git@mintra3.marienhaus.de:projects/soapconnect.git
        dir: gematik/soapconnect

  roles:
    - git

- hosts: wobpc
  become: false
  connection: local
  tags:
    - ansible

  vars:
    git_project_dir: /home/wob/ansible
    git_project_list:
      - url: git@mintra3.marienhaus.de:ansible/systems/medv.git
        dir: systems/medv
      - url: git@mintra3.marienhaus.de:ansible/systems/offline.git
        dir: systems/offline
      - url: git@mintra3.marienhaus.de:ansible/systems/intranet.git
        dir: systems/intranet
      - url: git@mintra3.marienhaus.de:ansible/systems/keycloak.git
        dir: systems/keycloak
      - url: git@mintra3.marienhaus.de:ansible/systems/chemocompile.git
        dir: systems/chemocompile

  roles:
    - git
